import type { Metadata } from "next";
import { Nav } from "@/components/nav/nav";
import { Inter, Playball } from 'next/font/google';
import { ColorConfig } from "@/components/tailwindConfig";
import "./globals.css";
import "./code.css";
import "./markdown.css";

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '700'],
});

const sixCaps = Playball({
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={
                `${inter.className}
                min-h-screen
                ${ColorConfig.root}`
            }>
                <div className="grid grid-cols-[24rem_1fr] auto-rows-auto">
                    <Nav className={sixCaps.className} />
                    <main className="col-span-2">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}